openai:
  api_key: 
  embedding_model: "text-embedding-3-small"
  classification_model: "gpt-3.5-turbo-0125"
  generation_model: "gpt-3.5-turbo-0125"
  temperature: 0.3
  max_tokens: 2000

vector_db:
  persist_directory: "./chroma_db"
  collection_name: "persona_chats"
  chunk_size: 1000
  chunk_overlap: 200

personas:
  - CFO
  - Teacher
  - Engineer
  - Healthcare Professional
  - Legal Advisor
  - Marketing Specialist
  - HR Manager
  - Data Scientist

retrieval:
  top_k: 5
  rerank_top_k: 3
  similarity_threshold: 0.7

logging:
  level: "INFO"
  format: "json"
  log_file: "logs/rag_chatbot.log"